# Generated by Django 3.2.7 on 2021-09-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Fad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('image_url', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decades', to='nostaldja.decade')),
            ],
        ),
    ]
